### ISSUE TITLE
Stream.anyMatch causes NoClassDefFoundError: hu/advancedweb/scott/runtime/track/StateRegistry

### ISSUE THREAD

**Issue by tom91136** [dodie/scott#22] opened 2016-11-05 02:28 UTC
While test driving scott, I've encountered a rather strange exception. If I use `Stream.anyMatch`, for example:

    new ArrayList<String>().stream().anyMatch(s -> false);

A `NoClassDefFoundError`  is thrown for some reason. I've checked scott's source but can't really find anything as I'm not familiar with java instrumentation. Perhaps you can give me some pointers as I'm really impressed with scott and would like to contribute.

The stacktrace:

    java.lang.Error:
       0|* ???  // NoClassDefFoundError: hu/advancedweb/scott/runtime/track/StateRegistry
       // removed , my source 
            at hu.advancedweb.scott.runtime.ScottReportingRule$1.evaluate(ScottReportingRule.java:30)
            at org.junit.rules.RunRules.evaluate(RunRules.java:20)
            at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
            at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
            at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
            at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
            at org.junit.runners.Suite.runChild(Suite.java:128)
            at org.junit.runners.Suite.runChild(Suite.java:27)
            at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
            at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
            at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
            at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
            at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
            at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
    Caused by: java.lang.NoClassDefFoundError: hu/advancedweb/scott/runtime/track/StateRegistry
            at java.util.stream.MatchOps.lambda$makeRef$0(MatchOps.java:97)
            at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
            at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
            at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
           
    	     // stuff that makes call to anyMatch...
    	   
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
            at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
            at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
            at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
            at hu.advancedweb.scott.runtime.ScottReportingRule$1.evaluate(ScottReportingRule.java:26)
            ... 31 more

**Comment by dodie** [comment] 2016-11-06 18:29
Thank you for trying Scott and submitting this issue! I have to agree, it's a very interesting exception, and it should not happen, as Scott shouldn't instrument methods in non-test classes, but somehow it does.

I've added debug logging to make it easier to see what's going on. If you build the upstream (2.0.1-SNAPSHOT) version, and set the **scottDebug** environment variable to true when running your tests (for example on unix: *export scottDebug="true"*), then Scott shows the visited and modified classes. For example:

```
Scott instrumentation: Visiting: hu/advancedweb/scott/StaticFieldRecordingTest.recordString
Scott instrumentation:  - instrumentToClearTrackedDataAndSignalStartOfRecording
Scott instrumentation:  - instrumentToTrackFieldState AccessedField [...]
Scott instrumentation:  - instrumentToTrackMethodStart at line 61
Scott instrumentation:  - instrumentToTrackFieldState AccessedField [...]
Scott instrumentation:  - instrumentToTrackFieldState AccessedField [...]
Scott instrumentation:  - instrumentToTrackFieldState AccessedField [...]
Scott instrumentation:  - instrumentToTrackFieldState AccessedField [...]
```

It's normal for Scott to visit non-test classes (such as java.util.stream.MatchOps), but it should not instrument them.
However it seems that lambdas are instrumented in all visited classes, and this causes the bug:

```
Scott instrumentation: Visiting: hu/advancedweb/scott/LambdaRecordingTest.lambda$test_stream$0
Scott instrumentation:  - instrumentToTrackVariableNameLocalVariableScope [var=0, name=s, start=0, end=27]
Scott instrumentation:  - instrumentToTrackVariableState of variable LocalVariableScope [var=0, name=s, start=0, end=27]
Scott instrumentation:  - instrumentToTrackMethodStart at line 27

...

Scott instrumentation: Visiting: java/util/stream/ReferencePipeline.lambda$count$2
Scott instrumentation:  - instrumentToTrackMethodStart at line 526
Scott instrumentation: Visiting: java/util/stream/ReferencePipeline.lambda$collect$1
Scott instrumentation:  - instrumentToTrackMethodStart at line 496
Scott instrumentation: Visiting: java/util/stream/ReferencePipeline.lambda$toArray$0
Scott instrumentation:  - instrumentToTrackMethodStart at line 444
Scott instrumentation: Visiting: java/util/stream/AbstractPipeline.lambda$opEvaluateParallelLazy$2
Scott instrumentation:  - instrumentToTrackMethodStart at line 704
Scott instrumentation: Visiting: java/util/stream/AbstractPipeline.lambda$wrapSpliterator$1
Scott instrumentation:  - instrumentToTrackMethodStart at line 529
Scott instrumentation: Visiting: java/util/stream/AbstractPipeline.lambda$spliterator$0
Scott instrumentation:  - instrumentToTrackMethodStart at line 364
Scott instrumentation: Visiting: java/util/function/Predicate.lambda$isEqual$3
Scott instrumentation:  - instrumentToTrackMethodStart at line 117
Scott instrumentation: Visiting: java/util/function/Predicate.lambda$or$2
Scott instrumentation:  - instrumentToTrackMethodStart at line 101
Scott instrumentation: Visiting: java/util/function/Predicate.lambda$negate$1
Scott instrumentation:  - instrumentToTrackMethodStart at line 80
Scott instrumentation: Visiting: java/util/function/Predicate.lambda$and$0
Scott instrumentation:  - instrumentToTrackMethodStart at line 69
Scott instrumentation: Visiting: java/util/stream/MatchOps.lambda$makeDouble$3
Scott instrumentation:  - instrumentToTrackMethodStart at line 186
Scott instrumentation: Visiting: java/util/stream/MatchOps.lambda$makeLong$2
Scott instrumentation:  - instrumentToTrackMethodStart at line 156
Scott instrumentation: Visiting: java/util/stream/MatchOps.lambda$makeInt$1
Scott instrumentation:  - instrumentToTrackMethodStart at line 126
Scott instrumentation: Visiting: java/util/stream/MatchOps.lambda$makeRef$0
Scott instrumentation:  - instrumentToTrackMethodStart at line 97
```

The *instrumentToTrackMethodStart* method should not be called when Scott visits
the lambdas in the java.util.stream classes.

In Scott, the *TransformationParameters* class controls what to instrument. The parameters are set by the *TestDiscoveryMethodVisitor* and the *DiscoveryClassVisitor*. The parameters are consumed by the *StateTrackingTestClassVisitor*.

Lambda methods should be instrumented only if they are defined in a test case that will be instrumented as well.
(Practically, this is almost equivalent with instrumenting all lambdas in a class, where there is at least one test case that will be instrumented.)
Currently the *DiscoveryClassVisitor* does not take this into account, if it sees a method with the *lamda$* in it's name, it marks it for tracking. This needs to be modified in order to get rid of this bug.

On a side note, I don't know yet why the *NoClassDefFoundError* happen if we try to call the *StateRegistry* from JDK classes.

**Comment by dodie** [comment] 2016-11-07 17:21
Continuing on the side note, I think the *NoClassDefFoundError* is caused by that the contents of the *rt.jar* (and other jars in the *<JAVA_HOME>/lib*) are loaded by the bootstrap classloader, while a different classloader is responsible to load the classes on the classpath. Classes loaded by the bootstrap classloader has no information about the classes loaded by the other classloaders, so injecting a static method call to them will blow up.

**Comment by tom91136** [comment] 2016-11-07 17:46
I've cloned repo and recreated the issue just in case. I can confirm that this is indeed a bug.

Regarding the bootstrap classloader issue, I've tried modifying the config:

    <argLine>-Xbootclasspath/p:${project.build.directory}/agents/scott-agent.jar</argLine>
    <argLine>-javaagent:${project.build.directory}/agents/scott-agent.jar</argLine>
    <workingDirectory>${basedir}/target</workingDirectory>

But that just disabled scott altogether with no error or warning.  

Looking at the JDK source of `Stream.anyMatch`, nothing rings a bell. Some little known language features were used such as `String[]::new` and local classes (classes embedded in methods) were used frequently but that shouldn't be a problem since other stream operations such as `Stream.collect` also goes through similar code path and no exception was thrown.

I'll see what I can do.

**Comment by dodie** [comment] 2016-11-09 21:07
The ```argLine``` setup might disable scott, because it misses one of its dependencies, for example JUnit. 
I investigated the issue a bit further, and came up with the following. The affected code path for ```collect``` and ```anyMatch``` can be different, and even two ```collect``` calls can execute different sequence of statements if different collectors are passed. I checked the following cases:

```
List<String> list = new ArrayList<String>();
list.add("a");
list.add("b");

// Case 1
list.stream().collect(Collectors.toList());

// Case 2
list.stream().collect(Collectors.groupingByConcurrent(String::length));
```

In Case 1, there is no error, because in this setup, no lamda is executed during this call. There is a lambda defined in ```Collectors.toList``` and another one in the ```collect```, but those are never called in this case.

In Case 2, there is an error, as there is an *accumulator* function defined in the ```groupingByConcurrent``` method as a lambda, that always executes.

Right now it seems that if a test calls anything in the JRE libs that has a lambda in it's execution path, it will crash. For example, the following test causes the same ```NoClassDefFoundError```, because maxBy returns a BinaryOperator defined by a lambda. Applying that lambda blows up, as it tries to execute its body: 

```
@Test
public void test() throws Exception {
	BinaryOperator.maxBy(new Comparator<String>() {
		@Override
		public int compare(String o1, String o2) {
			return 0; // Don't care.
		}
	}).apply("hello", "world");
}
```

But based on the above, I still think it's just a class loading issue. Regarding to that, I added a check to the ```TestClassTransformer``` class to leave the class alone, if it is being loaded by the Bootstrap classloader. It fixes the symptom, as all stream tests pass without an error. I disabled this fix temporarily because I don't want to mask the root cause of the problem, that the lambda instrumentation policy needs to be fixed.

**Comment by dodie** [comment] 2016-11-25 18:46
I've added the fixes for this issue, and a bunch of tests that use various JDK classes and Java8 features, such as lambdas and method references. I think the fixes solved the problem, but please feel free to poke around, and let me know if you find similar problems! Thanks!

**Closed by dodie** 2016-11-25 18:46 UTC
Labels: bug, recording

**Comment by dodie** [comment] 2016-11-25 19:05
Release 2.0.1 is complete, which contains the fix.

**Comment by tom91136** [comment] 2016-11-25 20:32
Thanks a lot, will give it a go ASAP.  Sorry about the silence as I was a bit busy working on other projects.
